# Generated by Django 5.1 on 2026-05-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_code_poll_polloption_pollresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollresponse',
            name='response_text',
        ),
    ]
