# Generated by Django 5.1 on 2026-05-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_pollresponse_response_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresponse',
            name='option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.polloption'),
            preserve_default=False,
        ),
    ]
