# Generated by Django 5.1 on 2026-05-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_emailcapture_feedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emailcapture',
            unique_together={('event', 'email')},
        ),
        migrations.RemoveField(
            model_name='emailcapture',
            name='workshop_updates',
        ),
    ]
