# Generated by Django 5.1 on 2026-05-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='question',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
