# Generated by Django 5.1 on 2026-05-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_question_is_visible_question_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
