# Generated by Django 5.1 on 2026-05-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_emailcapture_unique_together_and_more'),
        ('events', '0008_event_owner'),
    ]

    operations = [
    ]
