# Generated by Django 5.1 on 2026-05-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20260511_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
