# Generated by Django 5.1 on 2026-05-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_poll_is_active'),
        ('events', '0010_event_feedback_open'),
    ]

    operations = [
    ]
